### PR TITLE
build(dependabot): ignore minor and patch github-actions updates

### PR DESCRIPTION
**Pull request by Fdawgs**
See https://github.com/fastify/fastify/pull/3451

### CODE REVIEW

**Comment by jsumners** [comment]
Just go ahead and merge all of these @Fdawgs

**Comment by Fdawgs** [comment]
> Just go ahead and merge all of these @Fdawgs   

Will do, there are a few repos that require another reviewer before it can be merged. Can I ping you or someone to do those?

**Comment by zekth** [comment]
i ll approve

**Review by zekth — APPROVED** [review]

**Comment by Fdawgs** [comment]
Thanks @zekth!

**Pull request merged**
